plugins {
    alias(libs.plugins.androidApplication)
}

android {
    namespace 'info.bbmail.auvterminal'
    compileSdk 34

    defaultConfig {
        applicationId "info.bbmail.auvterminal"
        minSdk 28
        targetSdk 34
        versionCode 4
        versionName "3.1_GNSS_AE2000"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:deprecation"
    }

    applicationVariants.all {
        variant ->
            variant.outputs.each{
                output->
                    def applicationId = defaultConfig.applicationId
//            def versionCode = defaultConfig.versionCode
                    def versionName = defaultConfig.versionName
                    def date = new Date().format('yyMMdd')
//            def newName = "${applicationId}_r${versionCode}_v${versionName}_${date}.apk"
                    def newName = "${applicationId}_ver${versionName}_${date}.apk"
                    output.outputFileName = newName
            }
    }

}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation fileTree(include: ['*.jar'], dir: 'libs') // <- この一行を追加

}